Documentation:
- changed-files:
  - any-glob-to-any-file: docs/*

examples:
- changed-files:
  - any-glob-to-any-file: examples/*

package:
- changed-files:
  - any-glob-to-any-file: packages/repository/*

feature:
 - head-branch: ['^feature', 'feature']

bufix:
 - head-branch: ['^bugfix', 'bufix'] 