name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout the code
    - uses: actions/labeler@v2
      name: label action
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"